---
Parameters:
  AcquiredServiceRoleARN:
    Type: String
Resources:
  AcquiredRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: acquired-role
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref AcquiredServiceRoleARN
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateSnapshot
                  - ec2:DescribeVolumes
                Resource: "*"
